# Generated by Django 6.0.5 on 2026-05-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='ac_nbr_clb',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='ac_plc_clb',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
