# Generated by Django 6.1 on 2026-08-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_club_ac_nbr_clb_alter_club_ac_plc_clb'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ac_picture_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
